variables:
  IMAGE_NAME: airrloww/greenjetz
  IMAGE_TAG: earth-hero-app=1.0
# airrloww/greenjetz:earth-hero-app=1.0
stages:
  - test
  - build
  # - deploy

test_environment:
  stage: test
  image: node:14-alpine
  script:
    - apk update

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
  script:
    - docker build -t airrloww/greenjetz:earth-hero-app=1.0 .
    - docker push airrloww/greenjetz:earth-hero-app=1.0

