variables:
  IMAGE_NAME: airrloww/greenjetz
  IMAGE_TAG: earth-hero-app

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  # tags:
  #   - hero
  before_script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker run -d -p 8000:8000 $IMAGE_NAME:$IMAGE_TAG
    - nginx -t
    - docker ps -a 
    - service nginx restart

