variables:
  IMAGE_NAME: airrloww/greenjetz
  IMAGE_TAG: earth-hero-app

stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo $REGISTRY_PASSWORD | docker login -u $REGISTRY_USERNAME --password-stdin
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG

deploy_app:
  stage: deploy
  before_script:
    - chmod 400 $SSH_KEY
  script: 
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY -p $PORT $SERVER_USER@$IP_ADDRESS "
        docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD --password-stdin &&
        docker ps -aq | xargs docker stop | xargs docker rm &&
        docker run -d -p 8080:80 -v Caddyfile:/etc/caddy/Caddyfile $IMAGE_NAME:$IMAGE_TAG "